name:                testResourcesPruner
version:             0.1.0.0
github:              "psuszyns/testResourcesPruner"
license:             BSD3
author:              "Piotr Suszyński"
maintainer:          "psuszynski@private.com"
copyright:           "2018 Piotr Suszyński"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/psuszyns/testResourcesPruner#readme>

dependencies:
- base >= 4.7 && < 5
- process >= 1.6 && < 1.7
- bytestring >= 0.10.8.2 && < 0.11
- directory >= 1.3.0.2 && < 1.4
- optparse-applicative >= 0.14.2.0 && < 0.15

library:
  source-dirs: src

executables:
  testResourcesPruner-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - testResourcesPruner

tests:
  testResourcesPruner-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - testResourcesPruner
